# MoveIt-specific simulation settings
moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_

# Settings for ros_control control loop
generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01

hardware_interface:
    joints:
        - joint_a1
        - joint_a2
        - joint_a3
        - joint_a4
        - joint_a5
        - joint_a6
    sim_control_mode: 1  # 0: position, 1: velocity
        
    
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
# gazebo_ros_control:
#   pid_gains:
#     joint_a1: {p: 100, i: 100, d: 500.0}
#     joint_a2: {p: 100.0, i: 100, d: 2000.0}
#     joint_a3: {p: 100.0, i: 50, d: 1000.0}
#     joint_a4: {p: 100.0, i: 50, d: 200.0}
#     joint_a5: {p: 100.0, i: 50, d: 70.0}
#     joint_a6: {p: 100.0, i: 50, d: 70.0}


kr16_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
  gains:
      joint_a1: {p: 1000.00, i: 0, d: 0}
      joint_a2: {p: 1000.00, i: 0, d: 0}
      joint_a3: {p: 1000.00, i: 0, d: 0}
      joint_a4: {p: 1000.00, i: 0, d: 0}
      joint_a5: {p: 1000.00, i: 0, d: 0}
      joint_a6: {p: 1000.00, i: 0, d: 0}
  constraints:
        goal_time: 2.0
  state_publish_rate: 25     
  
controller_list:
  - name: kr16_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6

 

# joint1_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_a1
  #   pid: {p: 1000.00, i: 200.00, d: 200.00}
  # joint2_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_a2
  #   pid: {p: 1000.00, i: 200.00, d: 200.00}
  # joint3_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_a3
  #   pid: {p: 1000.00, i: 200.00, d: 200.00}
  # joint4_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_a4
  #   pid: {p: 1000.00, i: 200.00, d: 200.00}
  # joint5_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_a5
  #   pid: {p: 1000.00, i: 200.00, d: 200.00}
  # joint6_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_a6
  #   pid: {p: 1000.00, i: 200.00, d: 200.00}

